Link GitHub accounts
OpenRailAssociation/technical-committee pull request #115
Opened 2024-08-13 09:20 UTC by cornelius

2024-08-13 11:24 UTC, cornelius commented
Todo: Add Max as representative of the OpenRail Team as permanent guest.
Todo: Change Chair to Loic

2024-08-13 11:42 UTC, mxmehl requested changes
Added myself to the list

2024-08-13 11:42 UTC, mxmehl commented on README.md
> +* [Tristram Gräbener](https://github.com/Tristramg) (liblrs)
```suggestion
* [Tristram Gräbener](https://github.com/Tristramg) (liblrs)
* [Max Mehl](https://github.com/mxmehl) (Permanent guest, OpenRail Team's Technical Administration Manager)
```

2024-08-14 10:59 UTC, mxmehl approved these changes

2024-08-15 07:07 UTC, merged